# Numpy Array

In [1]:
import numpy as np

In [7]:
lst=[1,2,3,4]
#type(lst)
np.array(lst)
#type(np.array(lst))

array([1, 2, 3, 4])

In [13]:
#Two Dimesion
nested_lst = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
b=np.array(nested_lst)
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [15]:
#If two open and two close braces then 2d
b.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [16]:
#3 opening and 3 closing braces
b.reshape(2,6,1)

array([[[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]]])

In [19]:
#It means 3 rows of 2 cross 2 matrix
b.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [14]:
b.shape

(4, 3)

In [9]:
#It is a single dimension, 1d arraya=np.array(lst)
a.shape

(4,)

In [20]:
#Convert 1d to 2d
a.reshape(1,4)

array([[1, 2, 3, 4]])

In [22]:
#Convert 1d to 3d
a.reshape(4,1,1)

array([[[1]],

       [[2]],

       [[3]],

       [[4]]])

In [2]:
type(np.array(['Adi',2,3]))

numpy.ndarray

In [3]:
np.array([1,2,3.0])

array([1., 2., 3.])

In [ ]:
#Upcasting

In [23]:
#U6 means Unicode ##Google it, It is coming because mix datatype.
np.array(['Aditya',2,3])


array(['Aditya', '2', '3'], dtype='<U6')

In [ ]:
#Minimum

In [24]:
#ndmin, dimension = 5
np.array([1,2,3],ndmin=5)

array([[[[[1, 2, 3]]]]])

In [26]:
#complex is nothing but Imaginary part like complex no.
np.array([1,2,3],dtype=complex)
#np.array([1,2,3],dtype=np.float64)

array([1., 2., 3.])

In [ ]:
#Data-type consisting of more than one element:

In [27]:
#i means Integer, 1 byte = 8 bites, a = Zero terminates bytes

#i2 => 2*8 = 16, i8 => 8*8 = 64
x=np.array([(1,2),(3,4)],dtype=[('a','<i2'),('b','<i8')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [28]:
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [30]:
#b[row Index]
b[2]

array([7, 8, 9])

In [58]:
#b[1:3,-1:-4]

array([], shape=(2, 0), dtype=int32)

## Creating an Array from sub-classes:

In [68]:
#
issubclass(np.matrix,np.ndarray)

True

In [59]:
#matrix is subpart of numpy array
np.mat([1,3,4])

matrix([[1, 3, 4]])

In [62]:
np.array(np.mat([1,3,4]))

array([[1, 3, 4]])

In [61]:
type(np.mat([1,3,4]))

numpy.matrix

In [69]:
#Matrix is combiantion of rwo and column
np.mat('1,2;3,4')

matrix([[1, 2],
        [3, 4]])

### numpy.asarray

In [ ]:
#Convert the input to an array:

In [ ]:
#Convert a list into an array:

In [73]:
np.asarray([12,34,5])

array([12, 34,  5])

In [74]:
type(np.asarray([12,34,5]))

numpy.ndarray

In [75]:
arr1=np.array([12,13,14])

In [82]:
arr3=arr1

In [83]:
arr3[0]=64

In [84]:
arr3

array([64, 13, 14])

In [85]:
arr1

array([64, 13, 14])

In [76]:
arr2=np.asarray([12,13,14])

In [77]:
#arr1 is creating in diff loc and arr2 is another loc
arr1==arr2

array([ True,  True,  True])

In [78]:
#Is keyword is used to create in same loc
arr1 is arr2

False

In [81]:
#Example 
a=10
b=10
a is b

True

In [95]:
#if I am using a copy function then it will be a deep copy it will not reflect any chages to original data
#for example if I am using a = [1,2,3,4,5]
#this is a swallow copy
#if I will change any thing in this one then it will change original data as well
#l[0] = 234
#this will change my l as well
#but in case of using copy function it wont change my original data


In [86]:
#It will not copy in arr1
arr3=arr1.copy()

In [90]:
arr3[0]=10
arr3
arr1

array([64, 13, 14])

In [91]:
#np.array vs np.asarray
a=370
b=370
a is b

False

### numpy.fromfunction

In [92]:
np.fromfunction(lambda i,j: i==j, (3,3),dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [93]:
np.fromfunction(lambda i,j : i*j, (4,3),dtype=int)

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4],
       [0, 3, 6]])

In [ ]:
#Create a new 1-d array from an iterable object

In [94]:
iterable = (x*x for x in range(5))
iterable

<generator object <genexpr> at 0x00000249E7332660>

In [101]:
a=10
b=10

a is b

True

In [110]:
#Shallow copy vs Deep copy
#Shallow copy -> If I changed at one place but it is updated all
a=np.array([1,2,3,4])
b=a
b[0]=6

In [111]:
a

array([6, 2, 3, 4])

In [112]:
b

array([6, 2, 3, 4])

In [114]:
#Deep copy
a1=np.array([1,2,3,4])
b1=a.copy()
b1[0]=6

In [115]:
a1

array([1, 2, 3, 4])

In [116]:
b1

array([6, 2, 3, 4])

In [ ]:
#np.array vs np.asarray

In [2]:
import numpy as np
a=np.array([1,2,3,4])

In [3]:
np.asarray(a) is a #when you compare, it means it is referring to same array

True

In [4]:
np.array(a) is a #when you compare, it means, its is new memory loc.

False

In [5]:
a=np.asanyarray([1,2,3,4])

### Data Types

In [7]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
print('Type/class of this obj:',type(arr))
print('Hre is the vector:'arr)

SyntaxError: invalid syntax (<ipython-input-7-5b637c4ea960>, line 5)

In [11]:
import numpy as np

a=np.array([1,2,3,45])
a.ndim #printing dimension
a.size
a.shape
a.dtype

dtype('int32')

In [ ]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

### Arange and linspace

In [14]:
import numpy as np
np.arange(0,15,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [16]:
#import numpy as np
np.arange(0,14,2).reshape(1,7)

array([[ 0,  2,  4,  6,  8, 10, 12]])

In [19]:
#Return evenly spaced numbers over a specified interval.
np.linspace(0,10,50) #Step = 50, means 50 equal times 
#np.linspace(0,10,5) #Step means, how many equals numbers I want

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

### Matrix Creation

In [29]:
np.zeros((5,5))
np.ones((5,5))
np.eye((5))

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
print('Vector of Zeros: ',np.zeros(5))

Vector of Zeros:  [0. 0. 0. 0. 0.]


In [32]:
# Research pending from end from numpy doc
np.linspace(2.0,3.0,5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [33]:
np.linspace(2.0,3.0,5, endpoint=True)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [36]:
np.logspace(2.0,3.0,num=4,base=3)

array([ 9.        , 12.98024613, 18.72075441, 27.        ])

In [ ]:
#Extraxt a diagonal or extract a data from diagonal

In [39]:
x=np.arange(16).reshape((4,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [40]:
x.diagonal

<function ndarray.diagonal>

In [41]:
#Extract a diagonal or construct a diagonal array.
np.diag(x,k=2)

array([2, 7])

In [42]:
np.diag(x,k=-2)

array([ 8, 13])

In [43]:
np.diag(np.diag(x)) #Taking center element and remaining element is filled with 0

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [49]:
np.diagflat([[1,2],[3,4],[5,6]],k=-1).shape

(7, 7)

In [50]:
#An array with ones at and below the given diagonal and zeros elsewhere.
np.tri(3,5,-3,dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
###Random Number Geberation

In [53]:
np.random.randn(3,4) #Uniform distribution, range is between 0 to 1

array([[-0.64964274, -0.68799725, -0.54372891, -0.94711839],
       [ 0.28940107, -0.26579247, -1.41034977, -0.96009121],
       [ 0.20296245,  0.07433194,  0.47261647, -0.914657  ]])

In [54]:
np.random.rand(3,4) 

array([[0.16408517, 0.31852609, 0.29346816, 0.46596256],
       [0.07764514, 0.22333327, 0.70028502, 0.89857498],
       [0.21221468, 0.15412487, 0.15426098, 0.74098765]])

In [72]:
#Return random integers from `low` (inclusive) to `high` (exclusive).
np.random.randint(1,100)

2

In [77]:
np.random.randint(1,100,3)

array([78, 16, 68])

In [78]:
np.random.randint(1,100,6)

array([49, 29, 13, 98, 62, 36])

### Reshaping

In [ ]:
from numpy.random import randint as ri


In [81]:
np.random.randint(1,100,30).reshape(-1,6)

array([[12, 69, 66, 53, 87, 41],
       [52, 87, 17, 53,  5, 17],
       [47,  6, 69, 92, 32, 36],
       [ 8, 31, 38, 43, 38, 88],
       [76, 44, 72, 82, 30,  6]])

In [97]:
b2=np.random.randint(1,100,30).reshape(6,-44444)
b2

array([[77, 89, 65, 56, 61],
       [14, 76,  9, 78, 33],
       [80, 29, 62, 41, 10],
       [48, 89, 72, 12, 62],
       [49, 21, 26, 46, 63],
       [90,  9, 10, 68, 58]])

In [94]:
a=np.random.randint(0,100,30)
np.sort(a)
print(a)
a

[48 55 98 62 46  8 20 74 70 86 89 12  1 82 71 87 55 51 70 72 40 31 98 15
 83 38 38 87 66 48]


array([48, 55, 98, 62, 46,  8, 20, 74, 70, 86, 89, 12,  1, 82, 71, 87, 55,
       51, 70, 72, 40, 31, 98, 15, 83, 38, 38, 87, 66, 48])

In [98]:
#In mumpy, axis=0, taking as column wise and axis=1, row wise 
#a.max(axis=0)
b2.max(axis=1)

array([89, 78, 80, 89, 63, 90])

In [ ]:
print(a.max.)

In [ ]:
import pandas as pd
pd.pandas()